### ISSUE TITLE
Check if website is responding

### ISSUE THREAD

**Issue by xavier506** [edenia/antelope-tools#1131]
health check for websites (green check or red X ) would be great as some websites for BPs are not responding 

![Image](https://user-images.githubusercontent.com/5632966/214376367-c6f7265c-b3ca-415f-8729-18278e792c48.png)

**Comment by btcurenas** [comment]
**Epic:**
As a developer, I'd like to add a new health check to the website part at the BP section because it's valuable to know if this BP have to bring another end-point or figure out if we have problems from out end.

**Criteria:**
As the suggestion's mention, add a new health check for websites (green check or red X ) would be great as some websites for BPs are not responding.

**Tasks:**
